### ISSUE TITLE
Clicking buttons with space interferes with playing/pausing the reader

### ISSUE THREAD

**Issue by mhurm** [asdf57/ezeyes#30]
Adobe Spectrum's buttons can be clicked with spacebar when selected. This is great functionality accessibility-wise, but interferes with using spacebar as a keybind for playing/pausing the reader. We can either do:

- Rebind pause/play to some other key, perhaps Enter, and prevent spacebar from being used as a keybinding
- Modify buttons to disallow pressing them with space

I'd like to get someone's feedback as to which course of action we should take here.

**Comment by asdf57** [comment]
@mhurm Is this necessarily a bug or a desired feature? In my opinion, having the spacebar toggle selected items is crucial for users who navigate through the app using the Tab key. It's also a feature that's implied in the WAI-ARIA [spec](https://wai-aria-practices.netlify.app/aria-practices/#keyboard-interaction) itself.

**Comment by asdf57** [comment]
Marking as non-issue based on past discussions.
