### ISSUE TITLE
WPM UI Slider Does not Update When Keybind is Used 

### ISSUE THREAD

**Issue by mrigank351** [asdf57/ezeyes#44]
The WPM UI slider does not update in its physical location when the WPM of the application is increased/decreased through the use of the WPM keybind. Using the keybind also breaks the overall functionality of the slider itself. In order for the slider to work properly again, a new instance of the application must be opened, and the keybind must NOT be used.

Steps to Recreate Bug

1. Start the application with a file loaded in.
2. Un pause the application
3. Increase/Decrease WPM using the keybind 
4. Check WPM UI slider (Slider should still show 300 WPM)
5. Manipulate UI slider to confirm slider functionality is broken.

**Comment by asdf57** [comment]
Fixed in #49
